/* Nombres y apellidos */

const names = [
  "Emily",
  "Oliver",
  "Sophie",
  "Jack",
  "Chloe",
  "Harry",
  "Isabella",
  "William",
  "Mia",
  "James",
  "Emma",
  "Benjamin",
  "Amelia",
  "George",
  "Ava",
  "Noah",
  "Grace",
  "Lucas",
  "Ella",
  "Alexander",
  "Lily",
  "Ethan",
  "Olivia",
  "Daniel",
  "Charlotte",
  "Michael",
  "Harper",
  "Matthew",
  "Sophia",
  "Samuel",
  "Ruby",
  "Ryan",
  "Zoe",
  "Nathan",
  "Evelyn",
  "David",
  "Madison",
  "Joseph",
  "Hannah",
  "Thomas",
  "Aria",
  "Jacob",
  "Isla",
  "Leo",
  "Scarlett",
  "Ethan",
  "Abigail",
  "Max",
  "Ivy",
  "Joshua",
  "Aurora",
  "Liam",
  "Layla",
  "Henry",
  "Penelope",
  "Adam",
  "Mila",
  "Luke",
  "Victoria",
  "Caleb",
  "Elizabeth",
  "Dylan",
  "Stella",
  "Mason",
  "Willow",
  "Isaac",
  "Zoe",
  "Oscar",
  "Piper",
  "Sebastian",
  "Luna",
  "Samuel",
  "Grace",
  "Xavier",
  "Nova",
  "Levi",
  "Jasmine",
  "Cooper",
  "Esme",
  "Gabriel",
  "Elsie",
  "Elijah",
  "Imogen",
  "Logan",
  "Rose",
  "Jackson",
  "Maisie",
  "Aaron",
  "Emilia",
  "Hudson",
  "Aurora",
  "Julian",
  "Leah",
  "Arthur",
  "Jasmine",
  "Luca",
  "Georgia",
  "Felix",
  "Matilda",
  "Theodore",
  "Juan",
  "María",
  "Pablo",
  "Ana",
  "José",
  "Laura",
  "Carlos",
  "Sofía",
  "Alejandro",
  "Andrea",
  "Luis",
  "Marta",
  "Fernando",
  "Elena",
  "Diego",
  "Paula",
  "Manuel",
  "Clara",
  "Javier",
  "Carmen",
  "Daniel",
  "Lucía",
  "Jorge",
  "Patricia",
  "Raúl",
  "Beatriz",
  "Sergio",
  "Natalia",
  "Alberto",
  "Sara",
  "Antonio",
  "Rosa",
  "Miguel",
  "Raquel",
  "David",
  "Isabel",
  "Francisco",
  "Julia",
  "Rubén",
  "Diana",
  "Álvaro",
  "Adriana",
  "Eduardo",
  "Lorena",
  "Guillermo",
  "Victoria",
  "Ricardo",
  "Marina",
  "Víctor",
  "Inés",
  "Mario",
  "Alicia",
  "Gabriel",
  "Martina",
  "Oscar",
  "Elena",
  "Alfonso",
  "Lorena",
  "Iván",
  "Ángela",
  "Samuel",
  "Susana",
  "Rafael",
  "Miriam",
  "Javier",
  "Noelia",
  "Emilio",
  "Andrea",
  "Rubén",
  "Claudia",
  "Pedro",
  "Anaís",
  "Adrián",
  "Lorena",
  "Ángel",
  "Bárbara",
  "Jesús",
  "Laura",
  "Tomás",
  "Cristina",
  "Gonzalo",
  "Verónica",
  "Mateo",
  "Raquel",
  "Julián",
  "Irene",
  "Arturo",
  "Elena",
  "Óscar",
  "Laura",
  "Isaac",
  "Patricia",
  "Salvador",
  "Daniela",
  "Julián",
  "Lucía",
  "Roberto",
  "Clara",
  "Felipe",
  "Carmen",
];

const lastNames = [
  "Adams",
  "Armstrong",
  "Bailey",
  "Benson",
  "Black",
  "Bradley",
  "Brooks",
  "Burke",
  "Carlson",
  "Chapman",
  "Clark",
  "Coleman",
  "Collins",
  "Crawford",
  "Cunningham",
  "Daniels",
  "Davidson",
  "Duncan",
  "Dunn",
  "Ellis",
  "Fletcher",
  "Fox",
  "Franklin",
  "Garrett",
  "Gibson",
  "Grant",
  "Gray",
  "Griffin",
  "Hart",
  "Harvey",
  "Hawkins",
  "Hayes",
  "Hoffman",
  "Holland",
  "Holmes",
  "Howell",
  "Hudson",
  "Hunter",
  "Jacobs",
  "Jordan",
  "Keller",
  "Kennedy",
  "Lawson",
  "Little",
  "Marshall",
  "Mason",
  "May",
  "McCoy",
  "McDonald",
  "McKenzie",
  "Miles",
  "Montgomery",
  "Moore",
  "Morgan",
  "Morris",
  "Murray",
  "Myers",
  "Neal",
  "Nichols",
  "Olson",
  "Palmer",
  "Pearson",
  "Perkins",
  "Peters",
  "Peterson",
  "Porter",
  "Ray",
  "Reed",
  "Reeves",
  "Reid",
  "Rice",
  "Richards",
  "Richardson",
  "Riley",
  "Robbins",
  "Robertson",
  "Ross",
  "Ryan",
  "Shaw",
  "Simmons",
  "Simpson",
  "Sims",
  "Snyder",
  "Spencer",
  "Stanley",
  "Stevens",
  "Stevenson",
  "Sullivan",
  "Tate",
  "Terry",
  "Thornton",
  "Tucker",
  "Turner",
  "Tyler",
  "Vargas",
  "Wagner",
  "Walters",
  "Watkins",
  "Weaver",
  "Wheeler",
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Lewis",
  "Robinson",
  "Walker",
  "Hall",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Ramirez",
  "Campbell",
  "Mitchell",
  "Roberts",
  "Carter",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Morgan",
  "Peterson",
  "Cooper",
  "Reed",
  "Bailey",
  "Rivera",
  "Cooper",
  "Richardson",
  "Cox",
  "Howard",
  "Ward",
  "Flores",
  "Gutierrez",
  "Spencer",
  "Kim",
  "Foster",
  "Powell",
  "Long",
  "Patterson",
  "Hughes",
  "Washington",
  "Butler",
  "Simmons",
  "Foster",
  "Gonzales",
  "Bryant",
  "Alexander",
  "Russell",
  "Griffin",
  "Diaz",
  "Hayes",
  "Myers",
  "Ford",
  "Hamilton",
  "Graham",
  "García",
  "Rodríguez",
  "Martínez",
  "López",
  "Hernández",
  "Pérez",
  "Gómez",
  "Sánchez",
  "González",
  "Ramírez",
  "Torres",
  "Flores",
  "Díaz",
  "Ruiz",
  "Álvarez",
  "Jiménez",
  "Moreno",
  "Muñoz",
  "Romero",
  "Alonso",
  "Ruiz",
  "Navarro",
  "Rubio",
  "Molina",
  "Serrano",
  "Ortega",
  "Delgado",
  "Castro",
  "Morales",
  "Gutiérrez",
  "Ortiz",
  "Cruz",
  "Blanco",
  "Ramos",
  "Medina",
  "Guerrero",
  "Cabrera",
  "Vargas",
  "Calvo",
  "Molina",
  "León",
  "Herrera",
  "Pascual",
  "Arias",
  "Cordero",
  "Cano",
  "Núñez",
  "Mendoza",
  "Aguilar",
  "Bravo",
  "Guzmán",
  "Pineda",
  "Rivas",
  "Gallego",
  "Reyes",
  "Ferrer",
  "Casas",
  "Durán",
  "Cárdenas",
  "Moya",
  "Soler",
  "Cervantes",
  "Cáceres",
  "Fuentes",
  "Duarte",
  "Vidal",
  "Peralta",
  "Toledo",
  "Miranda",
  "Salazar",
  "Ochoa",
  "Monroy",
  "Beltrán",
  "Valencia",
  "Soto",
  "Sepúlveda",
  "Lara",
  "Paredes",
  "Zúñiga",
  "Arroyo",
  "Villa",
  "Ríos",
  "Guerra",
  "Lozano",
  "Zamora",
  "Quintero",
  "Calderón",
  "Robles",
  "Escobar",
  "Ponce",
  "Galán",
  "Villegas",
  "Palacios",
  "Tovar",
  "Lugo",
  "Chávez",
  "Luna",
  "Del Valle",
  "Rangel",
  "Escobedo",
];

/* Funciones varias */

function randomNumber(n) {
  return Math.floor(Math.random() * n);
}

function randomElement(arr) {
  return arr[randomNumber(arr.length)];
}

function generateRandomNames(n) {
  const generatedNames = [];
  for (let i = 0; i < n; i++) {
    const randomFullName =
      randomElement(lastNames) + ", " + randomElement(names);
    generatedNames.push(randomFullName);
  }
  generatedNames.sort();
  return generatedNames;
}

function appendLookUpName(name, index) {
  const nameElement = document.createElement("li");
  nameElement.textContent = name + " - " + index;
  namesList.appendChild(nameElement);
}

/* Setup del juego */
const n = 5000;
let searchedNums = [];

let randomNames = generateRandomNames(n);
const gaty = "Palma, Gaty";
randomNames.push(gaty);
randomNames.sort();

const inputNumber = document.getElementById("number");
const buscarBtn = document.getElementById("btn");
const newGameBtn = document.getElementById("new-game");
const titleDiv = document.getElementById("title");
const namesList = document.getElementById("nombres");
const winTitle = document.getElementById("win-popup");

const lookUpInst = document.createElement("h3");
let selectedNameIndex = randomNames.indexOf(gaty);

lookUpInst.textContent = "Encuentra a " + randomNames[selectedNameIndex];
titleDiv.appendChild(lookUpInst);

const counterHeading = document.createElement("h3");
titleDiv.appendChild(counterHeading);

function lookName() {
  const num = Math.floor(inputNumber.value);
  if (num >= 0 && num <= n && !searchedNums.includes(num)) {
    const name = randomNames[num - 1];
    searchedNums.push(num);
    appendLookUpName(name, num);
    searchCounter();
    winHandler(num);
  }
}

function winHandler(num) {
  if (num == selectedNameIndex + 1) {
    winTitle.classList.remove("hide");
    newGameBtn.classList.remove("hide");
    inputNumber.classList.add("hide");
    buscarBtn.classList.add("hide");
  }
}

function searchCounter() {
  counterHeading.textContent = "Has buscado: " + searchedNums.length + " veces";
}

function newGame() {
  selectedNameIndex = randomNumber(n);
  searchedNums = [];
  randomNames = generateRandomNames(n);
  lookUpInst.textContent = "Encuentra a " + randomNames[selectedNameIndex];
  namesList.innerHTML = "";
  searchCounter();
  inputNumber.value = "";
  winTitle.classList.add("hide");
  newGameBtn.classList.add("hide");
  inputNumber.classList.remove("hide");
  buscarBtn.classList.remove("hide");
}

buscarBtn.addEventListener("click", lookName);
inputNumber.addEventListener("keydown", (event) => {
  if (event.key === "Enter") {
    event.preventDefault();
    lookName();
  }
});

buscarBtn.addEventListener("click", lookName);
newGameBtn.addEventListener("click", newGame);
